<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN-CF1D5S3" failures="0" tests="3" name="Default test" time="31.917" errors="0" timestamp="2024-03-30T12:45:10 IST">
  <testcase classname="tests.AmazonTests" name="@BeforeTest setUpTest" time="31.788">
    <failure type="java.lang.AssertionError" message="Password field is displayed on the login page. expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Password field is displayed on the login page. expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at tests.AmazonTests.loginTest2(AmazonTests.java:79)
at tests.AmazonTests.setUpTest(AmazonTests.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest setUpTest -->
  <testcase classname="tests.AmazonTests" name="@AfterMethod getTestResult" time="-1.711782910308E9">
    <skipped/>
  </testcase> <!-- @AfterMethod getTestResult -->
  <testcase classname="tests.AmazonTests" name="@AfterMethod getTestResult" time="-1.711782910321E9">
    <skipped/>
  </testcase> <!-- @AfterMethod getTestResult -->
  <testcase classname="tests.AmazonTests" name="@AfterMethod getTestResult" time="-1.711782910333E9">
    <skipped/>
  </testcase> <!-- @AfterMethod getTestResult -->
  <testcase classname="tests.AmazonTests" name="@AfterTest tearDown" time="-1.711782910342E9">
    <skipped/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="tests.AmazonTests" name="amazonSearchTest" time="0.0">
    <skipped/>
  </testcase> <!-- amazonSearchTest -->
  <testcase classname="tests.AmazonTests" name="loginTest" time="0.0">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="tests.AmazonTests" name="loginTest2" time="0.0">
    <skipped/>
  </testcase> <!-- loginTest2 -->
</testsuite> <!-- Default test -->
